# @todo(sje): cert-manager may become optional in future, to allow for users to install their own version
apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: cert-manager
spec:
  chart:
    name: cert-manager
    chartVersion: 1.7.0
  helmVersion: v3
  useHelmInstall: true
  optionalValues:
    - when: '{{repl and (ConfigOptionEquals "cert_manager_enabled" "1") (ConfigOptionEquals "cert_manager_provider" "azure") }}'
      recursiveMerge: true
      values:
        cert-manager:
          extraArgs:
            - '--issuer-ambient-credentials=true'
