image: eu.gcr.io/gitpod-core-dev/dev/dev-environment:aledbf-go.4
workspaceLocation: gitpod/gitpod-ws.code-workspace
checkoutLocation: gitpod
ports:
  - port: 1337
    onOpen: open-preview
  - port: 3000
    onOpen: ignore
  - port: 3001
    onOpen: ignore
  - port: 3306
    onOpen: ignore
  - port: 4000
    onOpen: ignore
  # VNC
  - port: 5900
    onOpen: ignore
  # noVNC
  - port: 6080
    onOpen: ignore
  # Werft
  - port: 7777
    onOpen: ignore
  - port: 9229
    onOpen: ignore
  # Go proxy
  - port: 9999
    onOpen: ignore
  - port: 13001
    onOpen: ignore
  # Dev Theia
  - port: 13444
tasks:
  - name: Test Command
    init: export PREBUILD_PARAMS=${PREBUILD_PARAMS:-"100_500ms_30m_success"}; echo $PREBUILD_PARAMS; go run ./main.go $PREBUILD_PARAMS
vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - EditorConfig.EditorConfig
    - golang.go
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - stkb.rewrap
    - zxh404.vscode-proto3
    - matthewpi.caddyfile-support
    - heptio.jsonnet
    - timonwong.shellcheck
    - vscjava.vscode-java-pack
    - fwcd.kotlin
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
jetbrains:
  goland:
    prebuilds:
      version: stable
  intellij:
    prebuilds:
      version: stable

