packages:
  - name: docker
    type: docker
    deps:
      - dev/gpctl:app
      - dev/kubecdl:app
    argdeps:
      - imageRepoBase
    srcs:
      - gcloud-default-config
      - kubeconfig.yaml
      - mysql/*
    config:
      dockerfile: Dockerfile
      image:
        - ${imageRepoBase}/dev-environment:${version}
